events { worker_connections 1024; }

http {
    # Custom Log Format
    log_format swift_log '$time_iso8601 | $status | ${request_time}s | $upstream_addr | $request';
    access_log /var/log/nginx/access.log swift_log;

    upstream api_upstream {
        server api-service:3000;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://api_upstream;
            proxy_set_header X-Deployed-By swiftdeploy;
            proxy_pass_header X-Mode;

            # Use the timeout from manifest
            proxy_read_timeout 60s;

            # JSON Error handling
            error_page 502 503 504 /error.json;
        }

        location = /error.json {
            return 502 '{"error": "Bad Gateway", "code": 502, "service": "api-service", "contact": "admin@swiftdeploy.io"}';
            add_header Content-Type application/json;
        }
    }
}